### ISSUE TITLE
 Request the full source code for the UNet_XraySPI paper

### ISSUE THREAD

**Issue by syyl-fml** [AlfredoBellisario/UNet_XraySPI#1]
The author of the invitation:

Hello!

After reading your paper, I think I benefited a lot. I wish I could replicate some of the work in your paper. Having found some of the code, data sets, and weights for your paper, please provide the full source code for your paper so that you can replicate your work.
If you can provide, I will be very happy and grateful! Looking forward to your reply.

Adoring your readers.

**Comment by AlfredoBellisario** [comment]
Thank you for your interest in my work and for taking the time to reach out. 

The repository contains the information necessary to replicate the results, along with a README that provides details about the dataset, which is publicly hosted on CXIDB. After you opened this issue, I also added a link to the code used for orientation retrieval. This should be sufficient to reproduce the all the aspects of the work.

If you have specific questions or need clarification, feel free to ask. Otherwise, I believe the provided materials cover what is required in this issue.

I will close this issue now, but you’re welcome to open a new one if you encounter specific challenges while working with the repository. 

P.S.: I was in doubt if replying or not to this issue; I can see your account is new and I also received a strange e-mail with the exact same message. I decided to take advantage of your issue to add the link to EMC-code, but for the future I would appreciate it if you could share a bit more about yourself, such as your background, affiliation, and how this work aligns with your research or projects. This helps me better understand how my work is being used and fosters potential collaboration. Future "anonymous" or "strange" issues will be promptly deleted.

**Comment by syyl-fml** [comment]
> 感谢您对我的工作感兴趣并抽出时间与我们联系。
> 
> 存储库包含复制结果所需的信息，以及提供有关数据集详细信息的自述文件，该数据集在 CXIDB 上公开托管。在您打开此问题后，我还添加了一个指向用于方向检索的代码的链接。这应该足以再现作品的所有方面。
> 
> 如果您有具体问题或需要澄清，请随时提问。否则，我相信所提供的材料涵盖了本期的要求。
> 
> 我现在将关闭此问题，但如果您在使用存储库时遇到特定挑战，欢迎您打开一个新问题。
> 
> P.S.：我怀疑是否回复这个问题;我可以看到您的帐户是新的，我还收到了一封奇怪的电子邮件，其中包含完全相同的消息。我决定利用您的问题将链接添加到 EMC-code，但对于将来，如果您能分享更多关于您自己的信息，例如您的背景、隶属关系以及这项工作如何与您的研究或项目保持一致，我将不胜感激。这有助于我更好地了解我的工作是如何被使用的，并促进潜在的合作。未来的 “匿名” 或 “奇怪” 问题将被立即删除。

Dear authors,

Thank you very much for your reply, the data set, weights and part of the code of your paper have been found in the tips you published before, but not all the source code, if you can provide all the source code, I will be very grateful!

I am a new student in the field of image gap filling, and I want to learn and repeat your work. Due to my unproficiency in operation, I have not updated the relevant information for the time being. Thank you for not mind my interruption and giving me valuable suggestions

Thank you again for your adoring readers
